### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by jaeyun95** [iacercalixto/visualsem#1]
Hello!
Your paper was very impressive.
When will the code be released?

Thanks you:)

**Comment by houda96** [comment]
We are currently working on the documentation as well as some additional data things we are currently exploring on how to best release it, so stay tuned!

**Comment by jaeyun95** [comment]
oh thank you:)

**Comment by iacercalixto** [comment]
Hi @jaeyun95,

Thanks for waiting, and please check our updated repository! You can request to download VisualSem by filling in the form described in the README.md. :)

**Comment by jaeyun95** [comment]
oh! thank you:)
