### ISSUE TITLE
where is h5 file?

### ISSUE THREAD

**Issue by jaeyun95** [iacercalixto/visualsem#2]
i got 'No such file or directory' error, because .h5 file can't found.

where is h5 file? it doesn't  contain h5 file?

thank you!

**Comment by iacercalixto** [comment]
Hi @jaeyun95, could you please explain where and how did this error happen? Which is the h5 file raising the error? Thanks!

**Comment by jaeyun95** [comment]
i run 'retrieval_gloss.py', i got 'No such file or directory'(about .h5 file).
because, glosses.tgz doesn't have '.h5'file.

so i make .h5 file about gloss_file
it work successful!

**Comment by jaeyun95** [comment]
Oh sorry.
I didn't see the details of the'combine_sentencebert_glosses.py' file!
I completely solved it. Thank you!

**Comment by jaeyun95** [comment]
Oh sorry.
I didn't see the details of the'process_glosses_with_sentencebert.py' file!
I completely solved it. Thank you!
