### ISSUE TITLE
When will the image retrieval code be released? I look forward to it~

### ISSUE THREAD

**Issue by h-peng17** [iacercalixto/visualsem#3]

**Comment by iacercalixto** [comment]
Hi, unfortunately we don't yet have an expected date to release the image retrieval module, but please stay tuned!

**Comment by h-peng17** [comment]
Thank you~

**Comment by floschne** [comment]
> Hi, unfortunately we don't yet have an expected date to release the image retrieval module, but please stay tuned!

Hi, are there any plans or updates regarding the image retrieval module? From the code currently available image retrieval is not possible as it is described in the README -- or am I missing something?
