### ISSUE TITLE
The lack of the password: Download nodes_1000.json and store it in ./data.

### ISSUE THREAD

**Issue by wnntju** [iacercalixto/visualsem#5]
when I will download nodes_1000.json and store it in ./data. It prompts me to enter the password.

**Comment by ZYMblog** [comment]
> when I will download nodes_1000.json and store it in ./data. It prompts me to enter the password.

I have the same question. Did you solve it?

**Comment by iacercalixto** [comment]
Hi wnntju and ZYMblog, could you please send me an email requesting the password using your institutional (e.g. university)  email addresses? I will send you the password by email to conform to the data license agreement. Thank you!

**Comment by ZYMblog** [comment]
> Hi wnntju and ZYMblog, could you please send me an email requesting the password using your institutional (e.g. university) email addresses? I will send you the password by email to conform to the data license agreement. Thank you!

Thank you for your answer, I have sent an email to you using my school email addresses.

**Comment by houda96** [comment]
@iacercalixto Could you maybe add a sentence in the README about this (to avoid issues on this in the future)?
