### ISSUE TITLE
Image Retrieval Module

### ISSUE THREAD

**Issue by floschne** [iacercalixto/visualsem#6]
**Is your feature request related to a problem? Please describe.**
No, it is not really a problem. It is only a missing function

**Describe the solution you'd like**
I'd like to retrieve the top-k nodes for image queries. Basically the same as you've provided for glosses :-)

**Additional context**
Hi, thanks for open-sourcing this great dataset! Are there any plans or updates regarding the image retrieval module? From the code currently available image retrieval is not possible as it is described in the README -- or am I missing something?

**Comment by iacercalixto** [comment]
Hi, unfortunately we don't yet have an expected date to release the image retrieval module, and no plans to do so in the near future. We will update things here if this changes in the future. Thanks!
