### ISSUE TITLE
which neighbor nodes are updated to the node pool?

### ISSUE THREAD

**Issue by bigbrother001** [iacercalixto/visualsem#7]
Thanks for the open-source code! While, I wonder about how to get top10 neighbour nodes for each node in the initial node pool after filter out images.
It is said that "We prioritize visually relevant nodes with a larger number of images, nodes that include as many diverse relation types as possible, and especially nodes with less frequent relation types" in the paper, could you give more details, or show me in which part of the code?

**Comment by houda96** [comment]
You can check the dataset_creation/extract_nodes.py and then the create_entries function. This gives weights to certain relations etc. You can also check the first version of the paper in the appendix A Node Features (https://arxiv.org/pdf/2008.09150v1.pdf) where it is discussed in more details as well.

**Comment by bigbrother001** [comment]
Thanks very much. I close the issue.
